branch-defaults:
  production:
    environment: personality-project-api-server
  # (optional) Other branch-specific settings
  # (e.g. if you want a staging environment)
  # master:
  #  environment: mywebapp-api-staging
global:
  application_name: personlaity-project-api
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Docker running on 64bit Amazon Linux 2/3.2.0
  default_region: ap-northeast-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
